#!/bin/bash
set -euo pipefail
TAG="codex"
# shellcheck source=scripts/lib/common.sh
source "$(cd "$(dirname "$0")" && pwd)/lib/common.sh"

usage() {
  cat <<'USAGE'
Usage: scripts/codex.sh [--dry-run] [--non-interactive]

Installs/normalizes Codex CLI config and Codex skills.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run)
      DRY_RUN=true
      ;;
    --non-interactive)
      NON_INTERACTIVE=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      warn "unknown argument: $1"
      usage >&2
      exit 2
      ;;
  esac
  shift
done

info "Setting up Codex CLI..."

CODEX_CONFIG_DIR="${CODEX_HOME:-$HOME/.codex}"
CODEX_SHARED_CONFIG="$DOTFILES_DIR/configs/codex/config.toml"
CODEX_SHARED_AGENTS="$DOTFILES_DIR/configs/AGENTS.md"
CODEX_AGENTS_FRAGMENT="$DOTFILES_DIR/configs/codex/AGENTS.md"
CODEX_AGENTS_MARKER="GENERATED by scripts/codex.sh"
CODEX_CMUX_SKILL_REPO="https://github.com/manaflow-ai/cmux.git"
CODEX_CMUX_SKILL_PATH="skills/cmux"

sanitize_codex_shared_config() {
  local config_file="$CODEX_SHARED_CONFIG"
  [ -f "$config_file" ] || return 0

  local tmp_file
  tmp_file=$(mktemp)
  awk '
    # Machine-local state sections — must never live in the shared template.
    # Keep in sync with extract_machine_local_codex_sections below.
    /^\[/ {
      drop = ($0 ~ /^\[projects\."/ || $0 ~ /^\[marketplaces\./ || $0 ~ /^\[plugins\./ || $0 ~ /^\[hooks\.state/ || $0 ~ /^\[tui\./)
    }
    !drop { print }
  ' "$config_file" > "$tmp_file"

  if cmp -s "$tmp_file" "$config_file"; then
    rm -f "$tmp_file"
  else
    mv "$tmp_file" "$config_file"
    info "Removed machine-local Codex entries from shared config"
  fi
}

# Codex CLI uses config.toml as a mutable state store on top of user config:
# `codex plugin add` records [plugins."name@marketplace"], marketplace
# registration writes [marketplaces.*], project trust writes [projects."..."],
# and the one-time hook-trust prompt records [hooks.state.*] hashes. Those
# sections are machine-local by definition and must survive template
# refreshes — a plain template copy silently uninstalls every CLI-added
# plugin (e.g. ui-clone-skills@local, registered by the upstream installer
# that claude.sh runs earlier in the same pipeline) and re-triggers every
# hook-trust prompt.
extract_machine_local_codex_sections() {
  local config_file="$1"
  [ -f "$config_file" ] || return 0

  awk '
    # Keep in sync with the drop patterns in sanitize_codex_shared_config.
    /^\[/ {
      keep = ($0 ~ /^\[projects\."/ || $0 ~ /^\[marketplaces\./ || $0 ~ /^\[plugins\./ || $0 ~ /^\[hooks\.state/ || $0 ~ /^\[tui\./)
    }
    # Machine-local values survive refreshes; comments from retired setup tools
    # do not belong to the mutable-state contract.
    keep && $0 !~ /^[[:space:]]*#/ { print }
  ' "$config_file"
}

install_codex_config() {
  local dst="$CODEX_CONFIG_DIR/config.toml"
  local backup_dst tmp_file preserved=""

  ensure_dir "$CODEX_CONFIG_DIR"

  if $DRY_RUN; then
    info "[dry-run] cp $CODEX_SHARED_CONFIG -> $dst (preserving machine-local sections)"
    return 0
  fi

  tmp_file=$(mktemp)
  cp "$CODEX_SHARED_CONFIG" "$tmp_file"

  if [ -L "$dst" ]; then
    rm "$dst"
  elif [ -e "$dst" ]; then
    preserved="$(extract_machine_local_codex_sections "$dst")"
    if [ -n "$preserved" ]; then
      printf '\n%s\n' "$preserved" >> "$tmp_file"
    fi
    if cmp -s "$tmp_file" "$dst"; then
      rm -f "$tmp_file"
      return 0
    fi
    if grep -q "portable template" "$dst"; then
      warn "Refreshing managed Codex config at $dst"
    else
      backup_dst="$(next_backup_path "$dst")"
      warn "Backing up $dst -> $backup_dst"
      mv "$dst" "$backup_dst"
    fi
  fi

  # cat instead of mv: keeps the destination inode and mode stable.
  cat "$tmp_file" > "$dst"
  rm -f "$tmp_file"
  if [ -n "$preserved" ]; then
    info "Installed Codex config: $dst (template + preserved machine-local sections)"
  else
    info "Copied: $CODEX_SHARED_CONFIG -> $dst"
  fi
}


# ~/.codex/AGENTS.md 는 두 조각의 합성물이다. 공용 규약(configs/AGENTS.md)은
# Claude 와 공유하고, Codex 전용 계약만 configs/codex/AGENTS.md 가 소유한다.
# 통째로 추적해서 심링크하면 공용 규약이 두 파일에 복제되고, 한쪽만 고쳐도
# 아무것도 그것을 잡아내지 못한다 - llmwiki 스펙 8.4 가 피하려던 상태다.
#
# config.toml 과 달리 이 파일은 Codex 런타임이 쓰지 않으므로 생성물로 둬도
# 안전하다. 대신 사람이 손으로 고치면 다음 install 에서 조용히 덮이므로
# 헤더에 표식을 박고, 표식이 없는 파일은 지우지 않고 백업한다.
install_codex_agents_md() {
  local dst="$CODEX_CONFIG_DIR/AGENTS.md"
  local backup_dst tmp_file

  if [ ! -f "$CODEX_AGENTS_FRAGMENT" ] || [ ! -f "$CODEX_SHARED_AGENTS" ]; then
    warn "Codex AGENTS.md sources missing; skipping"
    return 0
  fi

  ensure_dir "$CODEX_CONFIG_DIR"

  if $DRY_RUN; then
    info "[dry-run] compose $CODEX_AGENTS_FRAGMENT + $CODEX_SHARED_AGENTS -> $dst"
    return 0
  fi

  tmp_file=$(mktemp)
  {
    printf '<!-- %s. Do not edit this file directly.\n' "$CODEX_AGENTS_MARKER"
    printf '     Codex-only part: configs/codex/AGENTS.md\n'
    printf '     Shared part:     configs/AGENTS.md (also used by Claude) -->\n\n'
    cat "$CODEX_AGENTS_FRAGMENT"
    printf '\n---\n\n'
    cat "$CODEX_SHARED_AGENTS"
  } > "$tmp_file"

  if [ -L "$dst" ]; then
    rm "$dst"
  elif [ -e "$dst" ]; then
    if cmp -s "$tmp_file" "$dst"; then
      rm -f "$tmp_file"
      return 0
    fi
    if grep -q "$CODEX_AGENTS_MARKER" "$dst"; then
      warn "Refreshing managed Codex AGENTS.md at $dst"
    else
      backup_dst="$(next_backup_path "$dst")"
      warn "Backing up $dst -> $backup_dst"
      mv "$dst" "$backup_dst"
    fi
  fi

  # cat instead of mv: keeps the destination inode and mode stable.
  cat "$tmp_file" > "$dst"
  rm -f "$tmp_file"
  info "Composed Codex AGENTS.md: $dst"
}


# claude-mem 은 Claude Code 플러그인으로 설치되지만 Codex 훅은 스스로 등록하지
# 않는다. 그 결과 Codex 세션은 두 달 가까이 하나도 기록되지 않았고, 아무 도구도
# 실패를 알리지 않았다 — 손으로 병합해서 복구했는데, 손으로 한 복구는 다음
# 머신에서 그대로 사라진다. 그래서 여기서 소유한다.
#
# 훅 명령은 플러그인이 배포하는 hooks/codex-hooks.json 을 그대로 쓴다. 명령을
# 이 저장소에 복사하면 claude-mem 이 경로 해석 방식을 바꿀 때마다 조용히 낡는다.
ensure_claude_mem_codex_hooks() {
  local hooks_file="$CODEX_CONFIG_DIR/hooks.json"
  local cache_root="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/plugins/cache/thedotmack/claude-mem"

  # stdout 은 호출부가 카운트로 읽는다. 로그는 전부 stderr 로 보낸다.
  [ -d "$cache_root" ] || { info "claude-mem plugin not installed — skipping Codex hook merge" >&2; return 0; }

  if $DRY_RUN; then
    info "[dry-run] merge claude-mem Codex hooks into $hooks_file" >&2
    return 0
  fi

  python3 - "$cache_root" "$hooks_file" <<'PY'
import json, sys
from pathlib import Path

cache_root, hooks_path = Path(sys.argv[1]), Path(sys.argv[2])


def version_key(d):
    base = d.name.split("-")[0]
    parts = [int(x) if x.isdigit() else 0 for x in base.split(".")[:3]]
    parts += [0] * (3 - len(parts))
    return (*parts, "-" not in d.name)


versions = [d for d in cache_root.iterdir()
            if d.is_dir() and d.name[:1].isdigit() and not (d / ".orphaned_at").exists()]
if not versions:
    print("no-plugin-version")
    raise SystemExit(0)

template = max(versions, key=version_key) / "hooks" / "codex-hooks.json"
if not template.is_file():
    print("no-template")
    raise SystemExit(0)

try:
    wanted = json.loads(template.read_text()).get("hooks", {})
except ValueError:
    # 읽을 수 없는 템플릿은 원하는 집합을 모른다는 뜻이다. 이 상태로
    # 진행하면 아래 정리 단계가 claude-mem 훅을 전부 지운다.
    print("bad-template")
    raise SystemExit(0)

if not any(g.get("hooks") for entries in wanted.values() for g in entries):
    # 빈 템플릿도 마찬가지다. "원하는 것이 없다" 가 아니라 "무엇을 원하는지
    # 모른다" 이므로 아무것도 지우지 않는다. 이것을 원하는 집합으로 취급하면
    # Codex 기록이 조용히 멈춘다 - 이 저장소가 두 달을 잃은 방식이다.
    print("empty-template")
    raise SystemExit(0)

try:
    # 0바이트는 손상이 아니라 아직 아무것도 없는 상태다. 잘린 쓰기로 흔히
    # 생기고 안전하게 대체할 수 있는데, 거부하면 병합이 영원히 막힌다.
    raw_live = hooks_path.read_text().strip() if hooks_path.is_file() else ""
    live = json.loads(raw_live) if raw_live else {}
except ValueError:
    # 읽을 수 없는 hooks.json 을 덮어쓰면 다른 도구의 훅까지 날아간다.
    # 가만히 두고 소리를 낸다 - 지금까지는 traceback 이 stderr 로만 가고
    # stdout 이 비어 호출부가 "할 일 없음" 으로 읽었다.
    print("bad-hooks-file")
    raise SystemExit(0)
live.setdefault("hooks", {})

# 이 파일에는 llmwiki, ui-clone 훅이 같은 이벤트에 공존한다. 그래서
# claude-mem 이 소유한 항목만 골라내야 하는데, 명령 문자열은 버전마다
# 바뀐다 - 실측으로 13.2.0 은 7개, 13.13.1 은 5개이고 겹치는 문자열이
# 하나도 없다. 추가만 하면 업그레이드할 때마다 옛 명령이 남아 같은
# 이벤트에서 두 번 발동하고, 아무것도 그것을 지우지 않는다.
#
# 소유 표식은 플러그인 캐시 경로다. 두 버전 템플릿 모두 전 명령이 이것을
# 담고 있고, 이 파일의 다른 도구 훅 중에는 하나도 없다.
MARKER = "thedotmack/claude-mem"

wanted_commands = {str(h.get("command", ""))
                   for entries in wanted.values()
                   for g in entries for h in g.get("hooks", [])}

removed = 0
for event, entries in list(live["hooks"].items()):
    kept_groups = []
    for group in entries:
        keep = []
        for hook in group.get("hooks", []):
            cmd = str(hook.get("command", ""))
            if MARKER in cmd and cmd not in wanted_commands:
                removed += 1
                continue
            keep.append(hook)
        if keep:
            kept_groups.append({**group, "hooks": keep})
    live["hooks"][event] = kept_groups

def commands(entries):
    return {str(h.get("command", ""))
            for g in entries for h in g.get("hooks", [])}


added = 0
for event, entries in wanted.items():
    have = commands(live["hooks"].get(event, []))
    for group in entries:
        fresh = [h for h in group.get("hooks", [])
                 if str(h.get("command", "")) not in have]
        if not fresh:
            continue
        live["hooks"].setdefault(event, []).append({**group, "hooks": fresh})
        added += len(fresh)

if added or removed:
    backup = hooks_path.with_suffix(f".json.pre-claude-mem-merge")
    if hooks_path.is_file() and not backup.exists():
        backup.write_text(hooks_path.read_text())
    hooks_path.parent.mkdir(parents=True, exist_ok=True)
    hooks_path.write_text(json.dumps(live, indent=2, ensure_ascii=False) + "\n")
print(added)
PY
}

# llmwiki 훅. Claude 쪽은 settings.json 이 저장소 심링크라 등록이 곧 커밋이지만
# ~/.codex/hooks.json 은 실파일이고 claude-mem/ui-clone 등 다른 도구도 같이
# 쓴다. 저장소로 추적되지 않으니 여기서 매번 확인한다.
ensure_llmwiki_codex_hooks() {
  local hooks_file="$CODEX_CONFIG_DIR/hooks.json"
  local dir="$DOTFILES_DIR/configs/llmwiki"

  [ -f "$dir/hook-session-start.sh" ] || { info "llmwiki hooks not in this checkout — skipping" >&2; return 0; }

  if $DRY_RUN; then
    info "[dry-run] register llmwiki hooks in $hooks_file" >&2
    return 0
  fi

  python3 - "$hooks_file" "$dir" <<'PY'
import json, sys
from pathlib import Path

hooks_path, hook_dir = Path(sys.argv[1]), Path(sys.argv[2])
wanted = {
    "SessionStart": hook_dir / "hook-session-start.sh",
    "UserPromptSubmit": hook_dir / "hook-user-prompt.sh",
}

live = json.loads(hooks_path.read_text()) if hooks_path.is_file() else {}
live.setdefault("hooks", {})

added = 0
for event, script in wanted.items():
    present = any(str(script) in str(h.get("command", ""))
                  for g in live["hooks"].get(event, []) for h in g.get("hooks", []))
    if present:
        continue
    live["hooks"].setdefault(event, []).append(
        {"hooks": [{"type": "command", "command": f'sh "{script}"', "timeout": 10}]})
    added += 1

if added:
    backup = hooks_path.with_suffix(".json.pre-llmwiki")
    if hooks_path.is_file() and not backup.exists():
        backup.write_text(hooks_path.read_text())
    hooks_path.parent.mkdir(parents=True, exist_ok=True)
    hooks_path.write_text(json.dumps(live, indent=2, ensure_ascii=False) + "\n")
print(added)
PY
}

install_codex_cmux_skill() {
  local skills_dir="$CODEX_CONFIG_DIR/skills"
  local dest="$skills_dir/cmux"
  local tmp_dir

  if $DRY_RUN; then
    info "[dry-run] install Codex cmux skill from $CODEX_CMUX_SKILL_REPO:$CODEX_CMUX_SKILL_PATH -> $dest"
    return 0
  fi

  if ! command -v git &>/dev/null; then
    warn "git not found; skipping Codex cmux skill install"
    return 0
  fi

  ensure_dir "$skills_dir"
  tmp_dir="$(mktemp -d)"

  if ! git clone --quiet --depth 1 --filter=blob:none --sparse "$CODEX_CMUX_SKILL_REPO" "$tmp_dir"; then
    rm -rf "$tmp_dir"
    warn "Failed to clone cmux repo; skipping Codex cmux skill install"
    return 0
  fi

  if ! git -C "$tmp_dir" sparse-checkout set "$CODEX_CMUX_SKILL_PATH" >/dev/null 2>&1; then
    rm -rf "$tmp_dir"
    warn "Failed to check out $CODEX_CMUX_SKILL_PATH; skipping Codex cmux skill install"
    return 0
  fi

  if [ ! -f "$tmp_dir/$CODEX_CMUX_SKILL_PATH/SKILL.md" ]; then
    rm -rf "$tmp_dir"
    warn "cmux skill missing SKILL.md upstream; skipping Codex cmux skill install"
    return 0
  fi

  if [ -e "$dest" ]; then
    rm -rf "$dest"
  fi

  cp -R "$tmp_dir/$CODEX_CMUX_SKILL_PATH" "$dest"
  rm -rf "$tmp_dir"
  info "Installed Codex cmux skill -> $dest"
}

if ! $DRY_RUN; then
  sanitize_codex_shared_config
fi
install_codex_config
install_codex_agents_md

if $DRY_RUN; then
  if command -v codex &>/dev/null; then
    info "[dry-run] codex --version"
    if $UPGRADE; then
      info "[dry-run] would: npm install -g @openai/codex@latest"
    fi
  else
    info "[dry-run] npm install -g @openai/codex"
  fi
  install_codex_cmux_skill
  ensure_claude_mem_codex_hooks >/dev/null
  ensure_llmwiki_codex_hooks >/dev/null
  if [ -x "$DOTFILES_DIR/scripts/skills.sh" ]; then
    bash "$DOTFILES_DIR/scripts/skills.sh" codex
  fi
  info "[dry-run] codex login status"
  info "Codex CLI setup done"
  exit 0
fi

# ── Install Codex CLI ──
#   npm install -g @openai/codex
codex_upgrade_failed=0
if command -v codex &>/dev/null; then
  CODEX_VERSION=$(codex --version 2>/dev/null || echo "unknown")
  info "Found codex ${CODEX_VERSION}"
  if $UPGRADE; then
    if command -v npm &>/dev/null; then
      info "Upgrading Codex CLI (--upgrade)..."
      if ! npm install -g @openai/codex@latest; then
        warn "Codex CLI upgrade failed"
        codex_upgrade_failed=1
      fi
    else
      warn "npm not found; cannot upgrade Codex CLI"
      codex_upgrade_failed=1
    fi
  fi
elif $DRY_RUN; then
  info "[dry-run] npm install -g @openai/codex"
else
  if ! command -v npm &>/dev/null; then
    warn "npm not found in PATH"
    warn "Run 'bash $DOTFILES_DIR/scripts/dev.sh' first, or install Codex with Homebrew: brew install --cask codex"
    exit 1
  fi

  if npm install -g @openai/codex; then
    info "Codex CLI installed"
  else
    warn "npm install -g @openai/codex failed"
    exit 1
  fi
fi

install_codex_cmux_skill

merged=$(ensure_claude_mem_codex_hooks || true)
llmwiki_added=$(ensure_llmwiki_codex_hooks || true)
[ "${llmwiki_added:-0}" = "0" ] || info "registered $llmwiki_added llmwiki hook(s) in Codex"
case "${merged:-0}" in
  0|"") : ;;
  no-plugin-version|no-template|empty-template|bad-template|bad-hooks-file)
    # 어느 쪽이든 원하는 훅 집합을 모른다. 그 상태에서 조용히 넘어가면
    # Codex 기록이 멈춘 것을 아무도 모른다.
    warn "claude-mem Codex hook template unusable ($merged) — Codex sessions will not be recorded"
    warn "  existing hooks were left untouched; check the plugin install" ;;
  *) info "merged $merged claude-mem hook(s) into Codex — Codex sessions are recorded again" ;;
esac
if [ -x "$DOTFILES_DIR/scripts/skills.sh" ]; then
  bash "$DOTFILES_DIR/scripts/skills.sh" codex
fi

# ── Codex auth check ──
if command -v codex &>/dev/null; then
  if codex login status >/dev/null 2>&1; then
    info "codex auth already configured"
  else
    echo ""
    warn "codex is not authenticated yet."
    echo ""
    echo "Run 'codex login' for ChatGPT sign-in, or pipe an API key with:"
    echo "  printenv OPENAI_API_KEY | codex login --with-api-key"
    echo "Use 'codex login --device-auth' for a headless device-code flow."
    echo ""

    if $DRY_RUN; then
      info "[dry-run] would run: codex login"
    elif $NON_INTERACTIVE; then
      warn "Non-interactive mode: skipped codex login. Run it manually before first use."
    else
      read -rp "Run 'codex login' now? (Y/n) " run_auth
      if [[ "$run_auth" =~ ^[Nn]$ ]]; then
        warn "Skipped. Run 'codex login' manually before first use."
      else
        codex login || warn "codex login exited non-zero — re-run manually if needed"
      fi
    fi
  fi
elif $DRY_RUN; then
  info "[dry-run] codex login status"
else
  warn "codex is still not available on PATH. Run 'codex login' after installing it."
fi

sanitize_codex_shared_config

if [ "$codex_upgrade_failed" -ne 0 ]; then
  warn "Codex upgrade completed with errors"
  exit 1
fi

info "Codex CLI setup done"
