#!/bin/bash
set -euo pipefail
TAG="codex"
# shellcheck source=scripts/lib/common.sh
source "$(cd "$(dirname "$0")" && pwd)/lib/common.sh"

usage() {
  cat <<'USAGE'
Usage: scripts/codex.sh [--dry-run] [--non-interactive]

Installs/normalizes Codex CLI config and Codex skills.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run)
      DRY_RUN=true
      ;;
    --non-interactive)
      NON_INTERACTIVE=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      warn "unknown argument: $1"
      usage >&2
      exit 2
      ;;
  esac
  shift
done

info "Setting up Codex CLI..."

CODEX_CONFIG_DIR="${CODEX_HOME:-$HOME/.codex}"
CODEX_SHARED_CONFIG="$DOTFILES_DIR/configs/codex/config.toml"
CODEX_SHARED_AGENTS="$DOTFILES_DIR/configs/AGENTS.md"
CODEX_AGENTS_FRAGMENT="$DOTFILES_DIR/configs/codex/AGENTS.md"
CODEX_AGENTS_MARKER="GENERATED by scripts/codex.sh"
CODEX_CMUX_SKILL_REPO="https://github.com/manaflow-ai/cmux.git"
CODEX_CMUX_SKILL_PATH="skills/cmux"

sanitize_codex_shared_config() {
  local config_file="$CODEX_SHARED_CONFIG"
  [ -f "$config_file" ] || return 0

  local tmp_file
  tmp_file=$(mktemp)
  awk '
    # Machine-local state sections — must never live in the shared template.
    # Keep in sync with extract_machine_local_codex_sections below.
    /^\[/ {
      drop = ($0 ~ /^\[projects\."/ || $0 ~ /^\[marketplaces\./ || $0 ~ /^\[plugins\./ || $0 ~ /^\[hooks\.state/ || $0 ~ /^\[tui\./)
    }
    !drop { print }
  ' "$config_file" > "$tmp_file"

  if cmp -s "$tmp_file" "$config_file"; then
    rm -f "$tmp_file"
  else
    mv "$tmp_file" "$config_file"
    info "Removed machine-local Codex entries from shared config"
  fi
}

# Codex CLI uses config.toml as a mutable state store on top of user config:
# `codex plugin add` records [plugins."name@marketplace"], marketplace
# registration writes [marketplaces.*], project trust writes [projects."..."],
# and the one-time hook-trust prompt records [hooks.state.*] hashes. Those
# sections are machine-local by definition and must survive template
# refreshes — a plain template copy silently uninstalls every CLI-added
# plugin (e.g. ui-clone-skills@local, registered by the upstream installer
# that claude.sh runs earlier in the same pipeline) and re-triggers every
# hook-trust prompt.
extract_machine_local_codex_sections() {
  local config_file="$1"
  [ -f "$config_file" ] || return 0

  awk '
    # Keep in sync with the drop patterns in sanitize_codex_shared_config.
    /^\[/ {
      keep = ($0 ~ /^\[projects\."/ || $0 ~ /^\[marketplaces\./ || $0 ~ /^\[plugins\./ || $0 ~ /^\[hooks\.state/ || $0 ~ /^\[tui\./)
    }
    # Machine-local values survive refreshes; comments from retired setup tools
    # do not belong to the mutable-state contract.
    keep && $0 !~ /^[[:space:]]*#/ { print }
  ' "$config_file"
}

install_codex_config() {
  local dst="$CODEX_CONFIG_DIR/config.toml"
  local backup_dst tmp_file preserved=""

  ensure_dir "$CODEX_CONFIG_DIR"

  if $DRY_RUN; then
    info "[dry-run] cp $CODEX_SHARED_CONFIG -> $dst (preserving machine-local sections)"
    return 0
  fi

  tmp_file=$(mktemp)
  cp "$CODEX_SHARED_CONFIG" "$tmp_file"

  if [ -L "$dst" ]; then
    rm "$dst"
  elif [ -e "$dst" ]; then
    preserved="$(extract_machine_local_codex_sections "$dst")"
    if [ -n "$preserved" ]; then
      printf '\n%s\n' "$preserved" >> "$tmp_file"
    fi
    if cmp -s "$tmp_file" "$dst"; then
      rm -f "$tmp_file"
      return 0
    fi
    if grep -q "portable template" "$dst"; then
      warn "Refreshing managed Codex config at $dst"
    else
      backup_dst="$(next_backup_path "$dst")"
      warn "Backing up $dst -> $backup_dst"
      mv "$dst" "$backup_dst"
    fi
  fi

  # cat instead of mv: keeps the destination inode and mode stable.
  cat "$tmp_file" > "$dst"
  rm -f "$tmp_file"
  if [ -n "$preserved" ]; then
    info "Installed Codex config: $dst (template + preserved machine-local sections)"
  else
    info "Copied: $CODEX_SHARED_CONFIG -> $dst"
  fi
}


# ~/.codex/AGENTS.md is a composite of two pieces. The shared contract
# (configs/AGENTS.md) is shared with Claude, and only the Codex-only contract is
# owned by configs/codex/AGENTS.md. Tracking and symlinking the whole file would
# duplicate the shared contract into two files, and an edit to only one of them
# would be caught by nothing - the state llmwiki spec 8.4 set out to avoid.
#
# Unlike config.toml, the Codex runtime never writes this file, so leaving it as
# a generated artifact is safe. But a hand edit would be silently overwritten by
# the next install, so a marker is stamped into the header and a file without
# that marker is backed up rather than deleted.
install_codex_agents_md() {
  local dst="$CODEX_CONFIG_DIR/AGENTS.md"
  local backup_dst tmp_file

  if [ ! -f "$CODEX_AGENTS_FRAGMENT" ] || [ ! -f "$CODEX_SHARED_AGENTS" ]; then
    warn "Codex AGENTS.md sources missing; skipping"
    return 0
  fi

  ensure_dir "$CODEX_CONFIG_DIR"

  if $DRY_RUN; then
    info "[dry-run] compose $CODEX_AGENTS_FRAGMENT + $CODEX_SHARED_AGENTS -> $dst"
    return 0
  fi

  tmp_file=$(mktemp)
  {
    printf '<!-- %s. Do not edit this file directly.\n' "$CODEX_AGENTS_MARKER"
    printf '     Codex-only part: configs/codex/AGENTS.md\n'
    printf '     Shared part:     configs/AGENTS.md (also used by Claude) -->\n\n'
    cat "$CODEX_AGENTS_FRAGMENT"
    printf '\n---\n\n'
    cat "$CODEX_SHARED_AGENTS"
  } > "$tmp_file"

  if [ -L "$dst" ]; then
    rm "$dst"
  elif [ -e "$dst" ]; then
    if cmp -s "$tmp_file" "$dst"; then
      rm -f "$tmp_file"
      return 0
    fi
    if grep -q "$CODEX_AGENTS_MARKER" "$dst"; then
      warn "Refreshing managed Codex AGENTS.md at $dst"
    else
      backup_dst="$(next_backup_path "$dst")"
      warn "Backing up $dst -> $backup_dst"
      mv "$dst" "$backup_dst"
    fi
  fi

  # cat instead of mv: keeps the destination inode and mode stable.
  cat "$tmp_file" > "$dst"
  rm -f "$tmp_file"
  info "Composed Codex AGENTS.md: $dst"
}


# claude-mem installs as a Claude Code plugin but does not register its Codex
# hooks itself. As a result not one Codex session was recorded for nearly two
# months and no tool reported the failure — it was recovered by a manual merge,
# and a manual recovery disappears on the next machine. So it is owned here.
#
# The hook commands are taken as-is from the hooks/codex-hooks.json the plugin
# ships. Copying the commands into this repo would let them go quietly stale
# every time claude-mem changes how it resolves paths.
ensure_claude_mem_codex_hooks() {
  local hooks_file="$CODEX_CONFIG_DIR/hooks.json"
  local cache_root="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/plugins/cache/thedotmack/claude-mem"

  # The caller reads stdout as a count. Send every log line to stderr.
  [ -d "$cache_root" ] || { info "claude-mem plugin not installed — skipping Codex hook merge" >&2; return 0; }

  if $DRY_RUN; then
    info "[dry-run] merge claude-mem Codex hooks into $hooks_file" >&2
    return 0
  fi

  python3 - "$cache_root" "$hooks_file" <<'PY'
import json, sys
from pathlib import Path

cache_root, hooks_path = Path(sys.argv[1]), Path(sys.argv[2])


def version_key(d):
    base = d.name.split("-")[0]
    parts = [int(x) if x.isdigit() else 0 for x in base.split(".")[:3]]
    parts += [0] * (3 - len(parts))
    return (*parts, "-" not in d.name)


versions = [d for d in cache_root.iterdir()
            if d.is_dir() and d.name[:1].isdigit() and not (d / ".orphaned_at").exists()]
if not versions:
    print("no-plugin-version")
    raise SystemExit(0)

template = max(versions, key=version_key) / "hooks" / "codex-hooks.json"
if not template.is_file():
    print("no-template")
    raise SystemExit(0)

try:
    wanted = json.loads(template.read_text()).get("hooks", {})
except ValueError:
    # An unreadable template means the wanted set is unknown. Proceeding from
    # here would make the cleanup step below delete every claude-mem hook.
    print("bad-template")
    raise SystemExit(0)

if not any(g.get("hooks") for entries in wanted.values() for g in entries):
    # Same for an empty template. It means "we do not know what is wanted", not
    # "nothing is wanted", so nothing is deleted. Treating it as the wanted set
    # would quietly stop Codex recording - the way this repo lost two months.
    print("empty-template")
    raise SystemExit(0)

try:
    # 0 bytes is not corruption but a state where nothing exists yet. It comes
    # commonly from a truncated write and can be safely replaced; refusing it
    # would block the merge forever.
    raw_live = hooks_path.read_text().strip() if hooks_path.is_file() else ""
    live = json.loads(raw_live) if raw_live else {}
except ValueError:
    # Overwriting an unreadable hooks.json would take other tools' hooks with
    # it. Leave it alone and make noise - until now the traceback went only to
    # stderr and stdout stayed empty, so the caller read it as "nothing to do".
    print("bad-hooks-file")
    raise SystemExit(0)
live.setdefault("hooks", {})

# In this file the llmwiki and ui-clone hooks coexist on the same events, so
# only the entries claude-mem owns must be picked out - but the command strings
# change from version to version. Measured: 13.2.0 has 7 and 13.13.1 has 5, with
# not a single string in common. Adding only would leave the old commands behind
# on every upgrade, firing twice on the same event, and nothing would remove
# them.
#
# The ownership marker is the plugin cache path. Every command in both version
# templates carries it, and no other tool's hook in this file does.
MARKER = "thedotmack/claude-mem"

wanted_commands = {str(h.get("command", ""))
                   for entries in wanted.values()
                   for g in entries for h in g.get("hooks", [])}

removed = 0
for event, entries in list(live["hooks"].items()):
    kept_groups = []
    for group in entries:
        keep = []
        for hook in group.get("hooks", []):
            cmd = str(hook.get("command", ""))
            if MARKER in cmd and cmd not in wanted_commands:
                removed += 1
                continue
            keep.append(hook)
        if keep:
            kept_groups.append({**group, "hooks": keep})
    live["hooks"][event] = kept_groups

def commands(entries):
    return {str(h.get("command", ""))
            for g in entries for h in g.get("hooks", [])}


added = 0
for event, entries in wanted.items():
    have = commands(live["hooks"].get(event, []))
    for group in entries:
        fresh = [h for h in group.get("hooks", [])
                 if str(h.get("command", "")) not in have]
        if not fresh:
            continue
        live["hooks"].setdefault(event, []).append({**group, "hooks": fresh})
        added += len(fresh)

if added or removed:
    backup = hooks_path.with_suffix(f".json.pre-claude-mem-merge")
    if hooks_path.is_file() and not backup.exists():
        backup.write_text(hooks_path.read_text())
    hooks_path.parent.mkdir(parents=True, exist_ok=True)
    hooks_path.write_text(json.dumps(live, indent=2, ensure_ascii=False) + "\n")
print(added)
PY
}

# llmwiki hooks. On the Claude side settings.json is a symlink into the repo, so
# registering is the same as committing, but ~/.codex/hooks.json is a real file
# shared with other tools such as claude-mem and ui-clone. It is not tracked by
# the repo, so it is verified here on every run.
ensure_llmwiki_codex_hooks() {
  local hooks_file="$CODEX_CONFIG_DIR/hooks.json"
  local dir="$DOTFILES_DIR/configs/llmwiki"

  [ -f "$dir/hook-session-start.sh" ] || { info "llmwiki hooks not in this checkout — skipping" >&2; return 0; }

  if $DRY_RUN; then
    info "[dry-run] register llmwiki hooks in $hooks_file" >&2
    return 0
  fi

  python3 - "$hooks_file" "$dir" <<'PY'
import json, sys
from pathlib import Path

hooks_path, hook_dir = Path(sys.argv[1]), Path(sys.argv[2])
wanted = {
    "SessionStart": hook_dir / "hook-session-start.sh",
    "UserPromptSubmit": hook_dir / "hook-user-prompt.sh",
}

live = json.loads(hooks_path.read_text()) if hooks_path.is_file() else {}
live.setdefault("hooks", {})

added = 0
for event, script in wanted.items():
    present = any(str(script) in str(h.get("command", ""))
                  for g in live["hooks"].get(event, []) for h in g.get("hooks", []))
    if present:
        continue
    live["hooks"].setdefault(event, []).append(
        {"hooks": [{"type": "command", "command": f'sh "{script}"', "timeout": 10}]})
    added += 1

if added:
    backup = hooks_path.with_suffix(".json.pre-llmwiki")
    if hooks_path.is_file() and not backup.exists():
        backup.write_text(hooks_path.read_text())
    hooks_path.parent.mkdir(parents=True, exist_ok=True)
    hooks_path.write_text(json.dumps(live, indent=2, ensure_ascii=False) + "\n")
print(added)
PY
}

install_codex_cmux_skill() {
  local skills_dir="$CODEX_CONFIG_DIR/skills"
  local dest="$skills_dir/cmux"
  local tmp_dir

  if $DRY_RUN; then
    info "[dry-run] install Codex cmux skill from $CODEX_CMUX_SKILL_REPO:$CODEX_CMUX_SKILL_PATH -> $dest"
    return 0
  fi

  if ! command -v git &>/dev/null; then
    warn "git not found; skipping Codex cmux skill install"
    return 0
  fi

  ensure_dir "$skills_dir"
  tmp_dir="$(mktemp -d)"

  if ! git clone --quiet --depth 1 --filter=blob:none --sparse "$CODEX_CMUX_SKILL_REPO" "$tmp_dir"; then
    rm -rf "$tmp_dir"
    warn "Failed to clone cmux repo; skipping Codex cmux skill install"
    return 0
  fi

  if ! git -C "$tmp_dir" sparse-checkout set "$CODEX_CMUX_SKILL_PATH" >/dev/null 2>&1; then
    rm -rf "$tmp_dir"
    warn "Failed to check out $CODEX_CMUX_SKILL_PATH; skipping Codex cmux skill install"
    return 0
  fi

  if [ ! -f "$tmp_dir/$CODEX_CMUX_SKILL_PATH/SKILL.md" ]; then
    rm -rf "$tmp_dir"
    warn "cmux skill missing SKILL.md upstream; skipping Codex cmux skill install"
    return 0
  fi

  if [ -e "$dest" ]; then
    rm -rf "$dest"
  fi

  cp -R "$tmp_dir/$CODEX_CMUX_SKILL_PATH" "$dest"
  rm -rf "$tmp_dir"
  info "Installed Codex cmux skill -> $dest"
}

if ! $DRY_RUN; then
  sanitize_codex_shared_config
fi
install_codex_config
install_codex_agents_md

if $DRY_RUN; then
  if command -v codex &>/dev/null; then
    info "[dry-run] codex --version"
    if $UPGRADE; then
      info "[dry-run] would: npm install -g @openai/codex@latest"
    fi
  else
    info "[dry-run] npm install -g @openai/codex"
  fi
  install_codex_cmux_skill
  ensure_claude_mem_codex_hooks >/dev/null
  ensure_llmwiki_codex_hooks >/dev/null
  if [ -x "$DOTFILES_DIR/scripts/skills.sh" ]; then
    bash "$DOTFILES_DIR/scripts/skills.sh" codex
  fi
  info "[dry-run] codex login status"
  info "Codex CLI setup done"
  exit 0
fi

# ── Install Codex CLI ──
#   npm install -g @openai/codex
codex_upgrade_failed=0
if command -v codex &>/dev/null; then
  CODEX_VERSION=$(codex --version 2>/dev/null || echo "unknown")
  info "Found codex ${CODEX_VERSION}"
  if $UPGRADE; then
    if command -v npm &>/dev/null; then
      info "Upgrading Codex CLI (--upgrade)..."
      if ! npm install -g @openai/codex@latest; then
        warn "Codex CLI upgrade failed"
        codex_upgrade_failed=1
      fi
    else
      warn "npm not found; cannot upgrade Codex CLI"
      codex_upgrade_failed=1
    fi
  fi
elif $DRY_RUN; then
  info "[dry-run] npm install -g @openai/codex"
else
  if ! command -v npm &>/dev/null; then
    warn "npm not found in PATH"
    warn "Run 'bash $DOTFILES_DIR/scripts/dev.sh' first, or install Codex with Homebrew: brew install --cask codex"
    exit 1
  fi

  if npm install -g @openai/codex; then
    info "Codex CLI installed"
  else
    warn "npm install -g @openai/codex failed"
    exit 1
  fi
fi

install_codex_cmux_skill

merged=$(ensure_claude_mem_codex_hooks || true)
llmwiki_added=$(ensure_llmwiki_codex_hooks || true)
[ "${llmwiki_added:-0}" = "0" ] || info "registered $llmwiki_added llmwiki hook(s) in Codex"
case "${merged:-0}" in
  0|"") : ;;
  no-plugin-version|no-template|empty-template|bad-template|bad-hooks-file)
    # Either way the wanted hook set is unknown. Passing over that silently
    # means nobody learns that Codex recording has stopped.
    warn "claude-mem Codex hook template unusable ($merged) — Codex sessions will not be recorded"
    warn "  existing hooks were left untouched; check the plugin install" ;;
  *) info "merged $merged claude-mem hook(s) into Codex — Codex sessions are recorded again" ;;
esac
if [ -x "$DOTFILES_DIR/scripts/skills.sh" ]; then
  bash "$DOTFILES_DIR/scripts/skills.sh" codex
fi

# ── Codex auth check ──
if command -v codex &>/dev/null; then
  if codex login status >/dev/null 2>&1; then
    info "codex auth already configured"
  else
    echo ""
    warn "codex is not authenticated yet."
    echo ""
    echo "Run 'codex login' for ChatGPT sign-in, or pipe an API key with:"
    echo "  printenv OPENAI_API_KEY | codex login --with-api-key"
    echo "Use 'codex login --device-auth' for a headless device-code flow."
    echo ""

    if $DRY_RUN; then
      info "[dry-run] would run: codex login"
    elif $NON_INTERACTIVE; then
      warn "Non-interactive mode: skipped codex login. Run it manually before first use."
    else
      read -rp "Run 'codex login' now? (Y/n) " run_auth
      if [[ "$run_auth" =~ ^[Nn]$ ]]; then
        warn "Skipped. Run 'codex login' manually before first use."
      else
        codex login || warn "codex login exited non-zero — re-run manually if needed"
      fi
    fi
  fi
elif $DRY_RUN; then
  info "[dry-run] codex login status"
else
  warn "codex is still not available on PATH. Run 'codex login' after installing it."
fi

sanitize_codex_shared_config

if [ "$codex_upgrade_failed" -ne 0 ]; then
  warn "Codex upgrade completed with errors"
  exit 1
fi

info "Codex CLI setup done"
