#!/bin/bash
set -euo pipefail
# shellcheck disable=SC2034 # consumed by scripts/lib/common.sh after source.
TAG="doctor"
# shellcheck source=scripts/lib/common.sh
# shellcheck disable=SC1091
source "$(cd "$(dirname "$0")" && pwd)/lib/common.sh"


cd "$DOTFILES_DIR"

status_ok=0
status_warn=0
status_fail=0

ok() { status_ok=$((status_ok + 1)); printf 'ok    %s\n' "$*"; }
warn_check() { status_warn=$((status_warn + 1)); printf 'warn  %s\n' "$*"; }
fail_check() { status_fail=$((status_fail + 1)); printf 'fail  %s\n' "$*"; }

check_command() {
  local name="$1" command_name="$2" required="${3:-required}"
  if command -v "$command_name" >/dev/null 2>&1; then
    ok "$name: $(command -v "$command_name")"
  elif [ "$required" = "optional" ]; then
    warn_check "$name missing (optional)"
  else
    fail_check "$name missing"
  fi
}

check_symlink() {
  local label="$1" expected="$2" actual="$3"
  if [ -L "$actual" ] && [ "$(readlink "$actual")" = "$expected" ]; then
    ok "$label linked"
  elif [ -e "$actual" ] || [ -L "$actual" ]; then
    warn_check "$label points elsewhere: $actual -> $(readlink "$actual" 2>/dev/null || printf 'real file')"
  else
    warn_check "$label missing: $actual"
  fi
}

# ~/.codex/AGENTS.md is not a symlink but a composite that codex.sh builds, so
# check_symlink cannot catch it. A missing marker means it was overwritten by
# hand or the install never ran, and then Codex alone runs without the shared
# contract - a failure that happens silently.
check_codex_agents_md() {
  local dst="${CODEX_HOME:-$HOME/.codex}/AGENTS.md"
  if [ ! -e "$dst" ]; then
    warn_check "codex AGENTS.md missing: $dst (run scripts/codex.sh)"
  elif grep -q "GENERATED by scripts/codex.sh" "$dst"; then
    ok "codex AGENTS.md composed"
  else
    warn_check "codex AGENTS.md unmanaged (hand-edited or stale): $dst"
  fi
}

check_git_state() {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    local dirty_count
    dirty_count="$(git status --porcelain | wc -l | tr -d ' ')"
    if [ "$dirty_count" = "0" ]; then
      ok "git working tree clean"
    else
      warn_check "git working tree has $dirty_count change(s)"
    fi
  else
    fail_check "not inside a git working tree"
  fi
}

check_lefthook() {
  if ! command -v lefthook >/dev/null 2>&1; then
    fail_check "lefthook missing"
    return
  fi
  ok "lefthook: $(lefthook version 2>/dev/null || printf 'installed')"
  if [ -x .git/hooks/pre-push ] && grep -q 'lefthook' .git/hooks/pre-push 2>/dev/null; then
    ok "lefthook pre-push hook installed"
  else
    warn_check "lefthook pre-push hook not installed; run lefthook install"
  fi
}

check_purplemux() {
  local bin real target
  bin="$(command -v purplemux 2>/dev/null || true)"
  if [ -z "$bin" ]; then
    warn_check "purplemux not on PATH (ok when unused on this machine)"
    return
  fi
  if [ ! -x "$bin" ]; then
    # `command -v` can still resolve a file that lost its exec bit via a stale
    # shell hash — a fake green that surfaces as a launchd crash loop.
    fail_check "purplemux resolved but not executable: $bin (chmod 755 or re-run services.sh)"
    return
  fi
  ok "purplemux: $bin"
  # Resolve the actual app path: through a services.sh-rendered shim (APP_DIR=)
  # or through symlinks. launchd cannot answer a TCC consent prompt, so an app
  # under ~/Documents|~/Desktop|~/Downloads hangs the LaunchAgent silently.
  target="$(sed -n 's/^APP_DIR="\(.*\)"$/\1/p' "$bin" 2>/dev/null | head -1)"
  if [ -z "$target" ]; then
    real="$(readlink -f "$bin" 2>/dev/null || printf '%s' "$bin")"
    target="$real"
  fi
  case "$target" in
    "$HOME/Documents"*|"$HOME/Desktop"*|"$HOME/Downloads"*)
      fail_check "purplemux app path under TCC-protected folder: $target (launchd hangs there — move it, e.g. ~/dev/)"
      ;;
    *)
      ok "purplemux app path outside TCC-protected folders: $target"
      ;;
  esac
}

check_local_bin_links() {
  local broken count local_bin_label
  local_bin_label="$HOME/.local/bin"
  broken="$(find "$HOME/.local/bin" -maxdepth 1 -type l ! -exec test -e {} \; -print 2>/dev/null || true)"
  if [ -z "$broken" ]; then
    ok "$local_bin_label has no broken symlinks"
    return
  fi
  count="$(printf '%s\n' "$broken" | wc -l | tr -d ' ')"
  warn_check "$local_bin_label has $count broken symlink(s): $(printf '%s' "$broken" | tr '\n' ' ')"
  warn_check "clean with: find ~/.local/bin -maxdepth 1 -type l ! -exec test -e {} \\; -delete"
}

case "${1:-}" in
  ""|--summary)
    ;;
  -h|--help)
    cat <<'USAGE'
Usage: scripts/doctor.sh [--summary]

Advisory dotfiles health snapshot. It does not mutate the machine and exits
non-zero only for failed required checks, not for warnings.
USAGE
    exit 0
    ;;
  *)
    warn "unknown argument: $1"
    exit 2
    ;;
esac

info "dotfiles health snapshot"
check_git_state

check_command "git" git
check_command "brew" brew
check_command "bats" bats optional
check_command "gitleaks" gitleaks optional
check_command "zsh" zsh
check_lefthook

if [ -x /Library/Developer/CommandLineTools/usr/libexec/git-core/git-credential-osxkeychain ]; then
  ok "Apple CLT git-credential-osxkeychain available"
else
  warn_check "Apple CLT git-credential-osxkeychain missing"
fi

check_symlink "HOME/.zshrc" "$DOTFILES_DIR/configs/.zshrc" "$HOME/.zshrc"
check_symlink "HOME/.tmux.conf" "$DOTFILES_DIR/configs/.tmux.conf" "$HOME/.tmux.conf"
check_symlink "HOME/.gitconfig" "$DOTFILES_DIR/configs/.gitconfig" "$HOME/.gitconfig"
check_symlink "HOME/.gitignore_global" "$DOTFILES_DIR/configs/.gitignore_global" "$HOME/.gitignore_global"
check_symlink "HOME/.agent/AGENTS.md" "$DOTFILES_DIR/configs/AGENTS.md" "$HOME/.agent/AGENTS.md"
check_codex_agents_md

check_purplemux
check_local_bin_links

# LLM tooling layer: install success and the change taking effect are different.
# Look at outcomes, not versions.
printf '\n-- llm tooling --\n'
while IFS=$'\t' read -r check state detail; do
  [ -z "$check" ] && continue
  case "$state" in
    ok|same) ok "$check: $detail" ;;
    missing|stale|error|local) warn_check "$check: $detail" ;;
    *)       printf 'info  %s: %s\n' "$check" "$detail" ;;
  esac
done < <(python3 "$DOTFILES_DIR/scripts/agent_tooling_doctor.py" 2>/dev/null)

printf '\nsummary: %s ok, %s warn, %s fail\n' "$status_ok" "$status_warn" "$status_fail"
[ "$status_fail" -eq 0 ]
